2022-11-13 19:02:41.422 | INFO     | __main__:main:91 - GuessNumberGame Server Start Successfully.
2022-11-13 19:04:45.169 | INFO     | __main__:route_http:54 - [main.route_http] request:{'haha': 'abc'}
2022-11-13 19:04:45.170 | ERROR    | __main__:route_http:69 - [main.route_http] remote_address('101.64.140.35', 58241) error=Traceback (most recent call last):
  File "/root/code/pythoncode/PYProject/GuessNumberGame/src/main.py", line 55, in route_http
    handler = appService.getHandler(data_d['api'])
KeyError: 'api'

2022-11-13 19:05:13.776 | INFO     | __main__:route_http:54 - [main.route_http] request:{'api': 'hello', 'haha': 'abc'}
2022-11-13 19:06:42.118 | DEBUG    | __main__:route_ngg:22 - conn:<websockets.legacy.server.WebSocketServerProtocol object at 0x7f77b8ad1eb0>
2022-11-13 19:07:11.206 | DEBUG    | __main__:route_ngg:22 - conn:<websockets.legacy.server.WebSocketServerProtocol object at 0x7f77b8a862e0>
