2022-11-13 20:53:54.604 | INFO     | __main__:main:91 - GuessNumberGame Server Start Successfully.
2022-11-13 20:53:58.220 | INFO     | __main__:route_http:54 - [main.route_http] request:{'api': 'login', 'haha': 'abc'}
2022-11-13 20:53:58.222 | ERROR    | __main__:route_http:69 - [main.route_http] remote_address('101.64.140.35', 58568) error=Traceback (most recent call last):
  File "/root/code/pythoncode/PYProject/GuessNumberGame/src/main.py", line 58, in route_http
    res = handler(data_d["data"])
KeyError: 'data'

2022-11-13 20:54:42.785 | INFO     | __main__:route_http:54 - [main.route_http] request:{'api': 'login', 'data': 'abc'}
2022-11-13 20:54:42.786 | ERROR    | __main__:route_http:69 - [main.route_http] remote_address('101.64.140.35', 58584) error=Traceback (most recent call last):
  File "/root/code/pythoncode/PYProject/GuessNumberGame/src/main.py", line 58, in route_http
    res = handler(data_d["data"])
  File "/root/code/pythoncode/PYProject/GuessNumberGame/src/AppService.py", line 51, in login
    username = data["username"]
TypeError: string indices must be integers

2022-11-13 20:55:29.738 | INFO     | __main__:route_http:54 - [main.route_http] request:{'api': 'login', 'data': {'username': 'zzz'}}
2022-11-13 20:56:24.883 | INFO     | __main__:route_http:54 - [main.route_http] request:{'api': 'register', 'data': {'username': 'zxz_test1', 'password': '', 'portrait': 'portrait'}}
2022-11-13 20:56:24.887 | INFO     | repository.crud:insert_without_id:149 - [PlayerPO::insert_without_id]:sql1=insert into player(name,type,score,portrait) values ('zxz_test1', 20, 0, 'portrait');
sql2=select max(id) from player;
2022-11-13 20:58:15.180 | INFO     | __main__:route_http:54 - [main.route_http] request:{'api': 'login', 'data': {'username': 'zxz_test1', 'password': '', 'portrait': 'portrait'}}
2022-11-13 20:58:15.182 | INFO     | repository.crud:selectUserStatus:204 - [Player::selectUserStatus]:sql=select status from userstatus where user_id = 221
2022-11-13 20:58:15.184 | INFO     | repository.crud:insertUserStatus:188 - [Player::insertUserStatus]:sql=insert into userstatus (`user_id`, `status`) VALUES (221, 1)
2022-11-13 21:06:13.180 | DEBUG    | __main__:route_ngg:22 - conn:<websockets.legacy.server.WebSocketServerProtocol object at 0x7fc7f4a0d7c0>
2022-11-13 21:06:15.057 | INFO     | __main__:route_ngg:32 - got a message:{"api":"create_room", "data":{"username":"zxz_test1","roomname":"我1"}}
2022-11-13 21:08:03.563 | INFO     | __main__:route_ngg:32 - got a message:{"api":"/create_room", "data":{"username":"zxz_test1","roomname":"我1"}}
2022-11-13 21:08:03.565 | ERROR    | __main__:route_ngg:43 - [main.route_ngg] remote_address('101.64.140.35', 63808) errpr=Traceback (most recent call last):
  File "/root/code/pythoncode/PYProject/GuessNumberGame/src/main.py", line 36, in route_ngg
    res = handler(data_d["data"])
TypeError: createRoom() takes 1 positional argument but 2 were given

